### PR TITLE
New implementation

### PR DESCRIPTION
**Pull request by dfdx**
As per discussion in #8, this PR completely replaces previous content of CUDNN.jl with the one in CUDNN2.jl.

### CODE REVIEW

**Comment by MikeInnes** [comment]
Not keeping the history then?

**Comment by dfdx** [comment]
History is still there in git. Or you mean having the old files side-by-side with the new ones?

**Comment by MikeInnes** [comment]
I mean the history of CUDNN2 itself, which I thought you wanted to keep.

**Comment by dfdx** [comment]
I'm not sure it's possible to replay the history of one repository onto another one. And there's actually not much to keep in CUDNN2 history.

**Comment by MikeInnes** [comment]
Like I said a few hours ago, you can do a merge commit that keeps both histories. See the branch https://github.com/JuliaGPU/CUDNN.jl/commits/cudnn2-2. That should keep your "git workflow" without breaking Pkg.

**Comment by dfdx** [comment]
Black magic! I didn't know it's possible, so misunderstood your first, sorry.

I couldn't do the same with existing `cudnn2` branch (perhaps, I need to take git course), so I just created [another PR](https://github.com/JuliaGPU/CUDNN.jl/pull/10).

**Pull request closed without merging**
